apiVersion: v1
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 5.0-SNAPSHOT
sources:
  - https://github.com/reportportal/k8s/reportportal
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io
engine: gotpl
