dependencies:
  - name: postgresql
    version: 3.9.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.installdep.enable

  - name: rabbitmq-ha
    version: 1.18.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.installdep.enable

  - name: elasticsearch
    version: 6.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.installdep.enable

  - name: minio
    version: 2.5.12
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: minio.installdep.enable