apiVersion: v1
kind: Service
metadata:
  name: analyzer-0
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.uat.name }}
    infoEndpoint: {{ $.Values.rp.infoEndpoint | default "/info"}}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-analyzer
  type: ClusterIP
