apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-uat
  template:
    metadata:
      labels:
        component: reportportal-uat
    spec:
      containers:
      - env:
        - name: RP_SESSION_LIVE
          value: "3600"
        - name: RP_DB_HOST
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: RP_DB_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: RP_DB_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: RP_DB_PASS
        {{ if .Values.postgresql.endpoint.cloudservice }}
          value: "{{ .Values.postgresql.endpoint.password }}"
        {{ else }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        {{ end }}
        {{ if .Values.minio.enabled }}
        - name: RP_BINARYSTORE_TYPE
          value: "minio"
        - name: RP_BINARYSTORE_MINIO_ENDPOINT
          value: "{{ .Values.minio.endpoint }}"
        - name: RP_BINARYSTORE_MINIO_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.minio.secretName }}"
              key: "accesskey"
        - name: RP_BINARYSTORE_MINIO_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.minio.secretName }}"
              key: "secretkey"
        {{ end }}
        name: uat
        image: "{{ .Values.uat.repository }}:{{ .Values.uat.tag }}"
        ports:
        - containerPort: 9999
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.uat.resources.requests.cpu }}
            memory: {{ .Values.uat.resources.requests.memory }}
          limits:
            cpu: {{ .Values.uat.resources.limits.cpu }}
            memory: {{ .Values.uat.resources.limits.memory }}
        readinessProbe:
          httpGet:
            path: "{{ .Values.rp.healthEndpoint }}"
            port: 9999
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
{{ include "nodeSelector" . | indent 8 }}